# Maintainer: Sander Danielsen <thelugal+aur gmail com>

pkgname="pacman-dl"
pkgver="0.6"
pkgrel="1"
pkgdesc="Periodically download packages from Arch mirrors"
arch=("any")
url="https://github.com/thelugal/pacman-dl"
license=("MIT")
provides=("pacman-dl")
optdepends=("libnotify: For desktop notifications")

source=(
    "https://raw.githubusercontent.com/TheLugal/${pkgname}/${pkgver}/files/${pkgname}"
    "https://raw.githubusercontent.com/TheLugal/${pkgname}/${pkgver}/files/${pkgname}.service"
    "https://raw.githubusercontent.com/TheLugal/${pkgname}/${pkgver}/files/${pkgname}.timer"
)


package() {
    cd "${srcdir}"
    install -Dm755 pacman-dl "${pkgdir}/usr/bin/pacman-dl"
    install -Dm644 pacman-dl.service "${pkgdir}/usr/lib/systemd/system/pacman-dl.service"
    install -Dm644 pacman-dl.timer "${pkgdir}/usr/lib/systemd/system/pacman-dl.timer"
}

# The sha256sums-block is generated by pre-commit git-hook
sha256sums=(
'dada50c5b0733b488887aee6cc4d3d905e366b9b3c276d0abd8add5ee35602a0' # pacman-dl
'04b5b1117b7d208e69ca8f58cb4e52f6412719d4f262f341a4596eb2584c9d4a' # pacman-dl.service
'dd7bdd3833efe9e34c1f39539380e15491a4fed03f73d0776d46a7aadf78d340' # pacman-dl.timer
)

